export const navBarMenuData = [
  {
    number: 0,
    label: '메인',
    boardType: 'all',
    bannerTitle: '',
    bannerDesc: '',
    path: '/',
  },
  {
    number: 1,
    label: '이론정보',
    boardType: 'theory',
    bannerTitle: '이론정보',
    bannerDesc: '간호학 이론과 학습 자료를 제공하는 공간',
    path: '/community/theory',
  },
  {
    number: 2,
    label: '실습정보',
    boardType: 'practice',
    bannerTitle: '실습정보',
    bannerDesc: '실습 관련 정보와 경험을 공유하는 곳',
    path: '/community/practice',
  },
  {
    number: 3,
    label: '국가고시준비',
    boardType: 'exam',
    bannerTitle: '국가고시준비',
    bannerDesc: '간호사 국가고시 대비를 위한 정보 제공',
    path: '/community/exam',
  },
  {
    number: 4,
    label: '취업정보',
    boardType: 'job',
    bannerTitle: '취업정보',
    bannerDesc: '간호사 취업 관련 정보 및 팁 제공',
    path: '/community/job',
  },
  {
    number: 5,
    label: '구인구직',
    boardType: 'employment',
    bannerTitle: '구인구직',
    bannerDesc: '간호사 구인구직 정보를 한눈에 확인',
    path: '/community/employment',
  },
  {
    number: 6,
    label: '이벤트',
    boardType: 'event',
    bannerTitle: '이벤트',
    bannerDesc: '커뮤니티 내 다양한 이벤트 소식 제공',
    path: '/community/event',
  },
  {
    number: 7,
    label: '공지사항',
    boardType: 'notice',
    bannerTitle: '공지사항',
    bannerDesc: '커뮤니티의 주요 공지와 소식을 안내',
    path: '/community/notice',
  },
];
